# build environment
FROM node:14.10.1-alpine as build
WORKDIR ./frontend
ENV PATH /frontend/node_modules/.bin:$PATH
COPY /frontend/package.json /frontend/package.json
RUN npm install --silent
RUN npm install @vue/cli@4.5.0 -g
COPY . /frontend
RUN npm run build

# production environment
FROM nginx:1.16.0-alpine
COPY --from=build /frontend/dist /usr/share/nginx/html
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/conf.d
EXPOSE 81
CMD ["nginx", "-g", "daemon off;"]